repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Updated version
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

# Temporarily disabled for development
# -   repo: https://github.com/golangci/golangci-lint
#     rev: v1.61.0
#     hooks:
#     -   id: golangci-lint
#         entry: golangci-lint run
#         types: [go]
#         pass_filenames: false

-   repo: local
    hooks:
    # Temporarily disabled for development
    # -   id: gosec
    #     name: gosec
    #     entry: gosec
    #     language: system
    #     types: [go]
    #     args: ["-exclude=G404", "./..."]

    -   id: terraform-fmt
        name: Terraform fmt
        description: Rewrites Terraform configuration files to canonical format.
        entry: terraform fmt
        language: system
        files: \.tf$
        pass_filenames: true

    -   id: go-fmt
        name: Go fmt
        description: Runs gofmt on Go files
        entry: gofmt -l -w
        language: system
        types: [go]
        pass_filenames: true

    -   id: go-test
        name: Go test
        description: Runs Go tests
        entry: go test
        language: system
        types: [go]
        pass_filenames: false
